site_name: Terrorluv
site_url: https://terrorluv.vercel.app
theme:
  name: material
  logo: icon.jpg
  favicon: icon.jpg
  features:
    - navigation.tracking
    #- navigation.instant
    #- navigation.instant.progress
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - toc.follow
    #- toc.integrate
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: pink
      accent: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: pink
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: overrides 
    
plugins:
  - search
  - encryptcontent:
      esm: true
      search_index: 'encrypted'
      encrypted_something:
            md-footer__inner: [nav, class]
            md-nav: [nav, class]
      #html_template_path: "overrides/decrypt-form.tpl.html"
      global_password: 'terror2025'
      remember_password: True
      title_prefix: 'test test'
      summary: 'Tempel der TerrorLuv Götter' 
      placeholder: 'Parole'
      decryption_failure_message: 'Hinfort, Ungläubiger! Das war das falsche Zauberwort.'
      encryption_info_message: 'Hinter dieser Tür wird den TerrorLuv Göttern gehuldigt. <br>Der Tempel ist nur für zertifizierte TerrorLuv-Götter-Jünger. Allen anderen: Good Luck!'
      #button_class: 'md-button'
      #password_button_text: 'ENTER'
      #password_button: True


extra_javascript:
  - javascripts/extra.js
  - javascripts/load-sheets.js
  - javascripts/hyperscript.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.number.min.js
  - javascripts/tablesort.js

  #- javascripts/tablesort.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/hyperscript.css
  
markdown_extensions:
  - toc:
      toc_depth: 3
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences